trikoder_oauth2:

    authorization_server:
        private_key: /private.key
        private_key_passphrase: '%env(PRIVATE_KEY_PASSPHRASE)'

        encryption_key: '%env(string:OAUTH2_ENCRYPTION_KEY)%'

    resource_server:
        public_key: /public.key

    persistence:
        doctrine: null
